services:
  frontend:
    image: santhr/elearning-frontend:latest

    restart: unless-stopped

    ports:
      - "80:80"
  node-exporter:
    image: prom/node-exporter:latest

    restart: unless-stopped

    ports:
      - "9100:9100"

    pid: host

    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro

    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--path.rootfs=/rootfs"