services:
  postgres:
    image: postgres:16
    restart: unless-stopped

    env_file:
      - .env.backend

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL","pg_isready -U elearning_user -d elearning_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: santhr/elearning-backend:latest

    restart: unless-stopped

    depends_on:
      postgres:
        condition: service_healthy

    env_file:
      - .env.backend

    ports:
      - "8081:8081"

    volumes:
      - backend_uploads:/app/uploads

  node-exporter:
    image: prom/node-exporter:latest

    restart: unless-stopped

    ports:
      - "9100:9100"

    pid: host

    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro

    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--path.rootfs=/rootfs"

volumes:
  postgres_data:
  backend_uploads: