spring:
  application:
    name: elearning-backend

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/elearning_db?options=-c%20timezone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:elearning_user}
    password: ${SPRING_DATASOURCE_PASSWORD:elearning_pass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      jdbc:
        time_zone: UTC

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migration: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

  endpoint:
    health:
      show-details: always

  metrics:
    tags:
      application: elearning-backend

    export:
      prometheus:
        enabled: true

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: 86400000

  admin:
    name: ${ADMIN_NAME:Admin}
    email: ${ADMIN_EMAIL:admin@elearning.com}
    password: ${ADMIN_PASSWORD}

  storage:
    type: ${STORAGE_TYPE:s3}

    local:
      upload-dir: ${UPLOAD_DIR:uploads}

    s3:
      bucket-name: ${AWS_S3_BUCKET_NAME}
      region: ${AWS_REGION:ap-south-1}
      presigned-url-expiration-minutes: ${S3_PRESIGNED_URL_EXPIRATION_MINUTES:10}